var data = {
	athletes : [
		{
      src: 'images/male.png',
      firstName: 'Patrick',
      lastName: 'Lee',
      sex: 'Male',
			team: "Team A",
			skill: "Varsity",
			mileTime: "5:45",
    },
    {
      src: 'images/female.png',
      firstName: 'Susan',
      lastName: 'Camire',
      sex: 'Female',
			team: "Team B",
			skill: "Varsity",
			mileTime: "6:34",
    },
    {
      src: 'images/male.png',
      firstName: 'Matthew',
      lastName: 'Marshall',
      sex: 'Male',
			team: "Team A",
			skill: "Varsity",
			mileTime: "6:00",
    },
    {
      src: 'images/female.png',
      firstName: 'Hope',
      lastName: 'Jenkins',
      sex: 'Female',
			team: "Team B",
			skill: "Varsity",
			mileTime: "6:39",
    },
    {
      src: 'images/male.png',
      firstName: 'Terry',
      lastName: 'Rodriguez',
      sex: 'Male',
			team: "Team A",
			skill: "Varsity",
			mileTime: "6:05",
    },
    {
      src: 'images/female.png',
      firstName: 'Peggy',
      lastName: 'Skinner',
      sex: 'Female',
			team: "Team A",
			skill: "Varsity",
			mileTime: "6:15",
    },
    {
      src: 'images/male.png',
      firstName: 'Joaquin',
      lastName: 'Lee',
      sex: 'Male',
			team: "Team B",
			skill: "Varsity",
			mileTime: "6:45",
    },
    {
      src: 'images/female.png',
      firstName: 'Alta',
      lastName: 'Davis',
      sex: 'Female',
			team: "Team A",
			skill: "Varsity",
			mileTime: "6:22",
    },
    {
      src: 'images/male.png',
      firstName: 'Travis',
      lastName: 'Beery',
      sex: 'Male',
			team: "Team B",
			skill: "Junior Varsity",
			mileTime: "7:01",
    },
    {
      src: 'images/female.png',
      firstName: 'Ula',
      lastName: 'Thomas',
      sex: 'Female',
			team: "Team B",
			skill: "Junior Varsity",
			mileTime: "8:02",
    },
    {
      src: 'images/male.png',
      firstName: 'Gary',
      lastName: 'Dixon',
      sex: 'Male',
			team: "Team B",
			skill: "Junior Varsity",
			mileTime: "7:52",
    },
    {
      src: 'images/female.png',
      firstName: 'Amy',
      lastName: 'Brantley',
      sex: 'Female',
			team: "Team B",
			skill: "Junior Varsity",
			mileTime: "7:45",
    },
    {
      src: 'images/male.png',
      firstName: 'John',
      lastName: 'Ropp',
      sex: 'Male',
			team: "Team B",
			skill: "Junior Varsity",
			mileTime: "7:25",
    },
    {
      src: 'images/female.png',
      firstName: 'Florence',
      lastName: 'Armbruster',
      sex: 'Female',
			team: "Team B",
			skill: "Junior Varsity",
			mileTime: "7:20",
    },
    {
      src: 'images/male.png',
      firstName: 'Johnnie',
      lastName: 'Tom',
      sex: 'Male',
			team: "Team B",
			skill: "Junior Varsity",
			mileTime: "7:18",
    },
    {
      src: 'images/female.png',
      firstName: 'Katherine',
      lastName: 'Caldwell',
      sex: 'Female',
			team: "Team B",
			skill: "Junior Varsity",
			mileTime: "7:15",
    },
	]
};
